"""
Marketing Agent — Content creation, SEO, social media, campaigns, and market research.
"""

from __future__ import annotations
import logging
import random
from typing import Any, Dict, List

from src.agents.base_agent import BaseAgent
from src.models.company_state import Action, CompanyState
from src.tools.content_tool import ContentTool
from src.tools.crm_tool import CRMTool

logger = logging.getLogger(__name__)


class MarketingAgent(BaseAgent):
    """
    The Marketing Agent builds brand presence and generates leads through:
    - Content marketing (blog posts, case studies)
    - Social media (LinkedIn, Twitter)
    - Email campaigns
    - Market research and targeting
    """

    def __init__(self, model: str = BaseAgent.DEFAULT_MODEL) -> None:
        super().__init__(
            name="Marketing",
            role="Chief Marketing Officer",
            model=model,
        )
        self._content_tool: ContentTool = None  # initialized in run_cycle
        self._crm_tool: CRMTool = None

    def get_system_prompt(self) -> str:
        return (
            "You are the CMO of IAN.AI Ventures, an AI automation company selling to SMBs.\n\n"
            "Your mission: Generate qualified leads and build brand authority to drive revenue growth.\n\n"
            "Products you market:\n"
            "  - AI Content Engine ($500/mo): Automates blog, social, email content for SMBs\n"
            "  - AI Sales Autopilot ($1,000/mo): Automates lead gen and outreach sequences\n"
            "  - AI Business Suite ($2,000/mo): Full AI automation stack\n\n"
            "Your responsibilities this cycle:\n"
            "1. Research the target market to understand best-fit segments.\n"
            "2. Create content (blog posts, social) that attracts ideal buyers.\n"
            "3. Launch at least one campaign to generate leads.\n"
            "4. Add new leads generated by campaigns to the CRM.\n"
            "5. Track and report campaign metrics.\n\n"
            "Focus on cost-effective tactics given our limited capital. "
            "Prioritize organic content and outbound to SMBs in marketing, technology, and consulting. "
            "Always call research_target_market first, then create content, then launch a campaign."
        )

    def get_tools(self) -> List[Dict[str, Any]]:
        return [
            {
                "name": "research_target_market",
                "description": "Research the best target market segments for our AI automation services.",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "industry": {
                            "type": "string",
                            "description": "Industry to research (e.g., marketing, technology, consulting, retail)",
                        },
                        "company_size": {
                            "type": "string",
                            "description": "Target company size: SMB, mid-market",
                        },
                    },
                    "required": [],
                },
            },
            {
                "name": "create_content",
                "description": "Create a piece of marketing content (blog post, social post, or email).",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "content_type": {
                            "type": "string",
                            "description": "Type: blog_post, social_post, email_sequence",
                        },
                        "topic": {"type": "string", "description": "Content topic or theme"},
                        "target_audience": {"type": "string", "description": "Who this is for"},
                    },
                    "required": ["content_type"],
                },
            },
            {
                "name": "launch_campaign",
                "description": "Launch a marketing campaign to generate leads.",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "campaign_name": {"type": "string"},
                        "campaign_type": {
                            "type": "string",
                            "description": "Type: content, email, social, paid, outbound",
                        },
                        "target_audience": {"type": "string"},
                        "budget": {
                            "type": "number",
                            "description": "Budget in USD (keep low, we have limited capital)",
                        },
                    },
                    "required": ["campaign_name", "campaign_type"],
                },
            },
            {
                "name": "track_campaign_metrics",
                "description": "Get metrics for all active campaigns.",
                "input_schema": {
                    "type": "object",
                    "properties": {},
                    "required": [],
                },
            },
            {
                "name": "add_leads_from_campaign",
                "description": "Add leads generated from a campaign to the CRM.",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "count": {
                            "type": "integer",
                            "description": "Number of leads to add",
                        },
                        "source": {
                            "type": "string",
                            "description": "Lead source: organic, paid, referral, outbound",
                        },
                        "industry": {
                            "type": "string",
                            "description": "Industry of the leads",
                        },
                    },
                    "required": ["count", "source"],
                },
            },
        ]

    def handle_tool_call(
        self, tool_name: str, tool_input: Dict[str, Any], state: CompanyState
    ) -> str:
        # Lazy init tools
        if self._content_tool is None:
            self._content_tool = ContentTool(state)
        if self._crm_tool is None:
            self._crm_tool = CRMTool(state)

        if tool_name == "research_target_market":
            return self._research_market(tool_input)
        elif tool_name == "create_content":
            return self._create_content(tool_input)
        elif tool_name == "launch_campaign":
            return self._content_tool.execute(
                "content_launch_campaign",
                {
                    "name": tool_input.get("campaign_name", "Campaign"),
                    "type": tool_input.get("campaign_type", "content"),
                    "target_audience": tool_input.get("target_audience", "SMB owners"),
                    "budget": tool_input.get("budget", 0),
                },
            )
        elif tool_name == "track_campaign_metrics":
            return self._track_campaigns(state)
        elif tool_name == "add_leads_from_campaign":
            return self._add_leads(tool_input, state)
        return f"Unknown marketing tool: {tool_name}"

    def _research_market(self, inp: Dict[str, Any]) -> str:
        industry = inp.get("industry", "marketing")
        size = inp.get("company_size", "SMB")
        insights = [
            f"Target market research: {industry} / {size}",
            "Key findings:",
            "  - 73% of SMBs want to automate marketing but lack resources",
            "  - Average SMB spends $800/mo on marketing tools (fragmented)",
            "  - Pain points: content creation (68%), lead generation (61%), follow-up (55%)",
            "  - Decision makers: Founder/CEO (55%), Marketing Manager (30%), Sales Manager (15%)",
            "  - Buying cycle: 2-4 weeks for Tier 1, 4-8 weeks for Tier 2/3",
            f"  - Best channels for {industry}: LinkedIn (42%), Cold Email (35%), Content SEO (23%)",
            "  - Average contract value expectations: $400-600/mo (Tier 1 is right-priced)",
            "Recommended ICP: Founder-led SMBs, 5-50 employees, $1M-$10M revenue, tech-savvy",
        ]
        return "\n".join(insights)

    def _create_content(self, inp: Dict[str, Any]) -> str:
        content_type = inp.get("content_type", "blog_post")
        topic = inp.get("topic", "AI automation for SMBs")
        audience = inp.get("target_audience", "SMB owners")

        if content_type == "blog_post":
            return self._content_tool.execute(
                "content_create_blog_post",
                {"topic": topic, "target_audience": audience},
            )
        elif content_type == "social_post":
            return self._content_tool.execute(
                "content_create_social_post",
                {"platform": "linkedin", "theme": "thought_leadership", "count": 3},
            )
        elif content_type == "email_sequence":
            return self._content_tool.execute(
                "content_create_email_sequence",
                {"sequence_type": "cold_outreach", "target_segment": audience, "emails_count": 3},
            )
        return f"Content type '{content_type}' created for topic: {topic}"

    def _track_campaigns(self, state: CompanyState) -> str:
        campaigns = state.campaigns
        if not campaigns:
            return "No campaigns running yet."
        lines = [f"Active Campaigns ({len(campaigns)}):"]
        for c in campaigns:
            lines.append(
                f"  [{c.id}] {c.name} | {c.type} | Status: {c.status} | "
                f"Leads: {c.leads_generated} | Cost: ${c.cost:.0f} | "
                f"Revenue: ${c.revenue_attributed:.0f}"
            )
        return "\n".join(lines)

    def _add_leads(self, inp: Dict[str, Any], state: CompanyState) -> str:
        count = min(inp.get("count", 3), 20)
        source = inp.get("source", "organic")
        industry = inp.get("industry", None)

        added = []
        for _ in range(count):
            lead = CRMTool.generate_random_lead(source=source)
            if industry:
                lead.industry = industry
            state.add_lead(lead)
            added.append(f"{lead.name} @ {lead.company}")

        return (
            f"Added {count} leads from {source} campaign:\n"
            + "\n".join(f"  - {l}" for l in added[:5])
            + (f"\n  ... and {count-5} more" if count > 5 else "")
        )

    def run_cycle(self, state: CompanyState) -> List[Action]:
        """Run one marketing cycle."""
        self.log_cycle_start(state)

        # Init tools with current state
        self._content_tool = ContentTool(state)
        self._crm_tool = CRMTool(state)

        context = {
            **state.to_summary_dict(),
            "active_campaigns": len(state.campaigns),
            "total_content_pieces": 0,
        }

        task = (
            f"Month {state.month} Marketing Cycle. "
            f"Current MRR: ${state.mrr:,.0f}. "
            f"We need to generate leads to grow MRR to ${state.target_mrr:,.0f}. "
            f"Research the market, create valuable content, launch a campaign, "
            f"and add at least 5 new leads to the pipeline. "
            f"Focus on high-quality leads with strong fit for our AI automation services."
        )

        result = self.run(task=task, context=context, state=state)

        state.agent_reports["Marketing"] = {
            "month": state.month,
            "leads_in_pipeline": len(state.leads),
            "active_campaigns": len(state.campaigns),
            "output_summary": result.output[:300],
        }

        self.log_cycle_end(result.actions_taken)
        return result.actions_taken
